version: '3.6'

services:
  dps-scheduler:
    image: texas-dps-scheduler:latest
    container_name: texas-dps-scheduler
    restart: on-failure
    volumes:
      - ./config.yml:/config.yml
    environment:
      - TZ=America/Chicago
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 10
        window: 120s
